/* High-fidelity product screens, drawn in HTML/CSS at real app size (1280×800 desktop, 390×844 phone) with sample
 * data. They are decorative illustrations ("Illustrative UI"), built as strings so the same markup can be injected
 * lazily on the client and rendered on the server for the case-study routes. Class names are scoped by app/editorial.css
 * under `.ui` / `.u-*`. */
const bars = () => [42, 64, 50, 78, 58, 88, 70, 95, 66].map((h) => `<i style="height:${h}%"></i>`).join('')
/* ================= High-fidelity product screens (illustrative UI with sample data) ================= */
const IC: Record<string, string> = {
	grid: '<path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z"/>', monitor: '<rect x="2" y="4" width="20" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>',
	play: '<rect x="2" y="4" width="20" height="14" rx="2"/><path d="M10 8l5 3-5 3z"/>', pulse: '<path d="M3 12h4l3-8 4 16 3-8h4"/>', code: '<path d="M8 6l-6 6 6 6M16 6l6 6-6 6"/>',
	shield: '<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/>', gear: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 00.3 1.8l.1.1a2 2 0 11-2.8 2.8l-.1-.1a1.7 1.7 0 00-1.8-.3 1.7 1.7 0 00-1 1.5V21a2 2 0 11-4 0v-.1a1.7 1.7 0 00-1.1-1.5 1.7 1.7 0 00-1.8.3l-.1.1a2 2 0 11-2.8-2.8l.1-.1a1.7 1.7 0 00.3-1.8 1.7 1.7 0 00-1.5-1H3a2 2 0 110-4h.1a1.7 1.7 0 001.5-1.1 1.7 1.7 0 00-.3-1.8l-.1-.1a2 2 0 112.8-2.8l.1.1a1.7 1.7 0 001.8.3H9a1.7 1.7 0 001-1.5V3a2 2 0 114 0v.1a1.7 1.7 0 001 1.5 1.7 1.7 0 001.8-.3l.1-.1a2 2 0 112.8 2.8l-.1.1a1.7 1.7 0 00-.3 1.8V9a1.7 1.7 0 001.5 1H21a2 2 0 110 4h-.1a1.7 1.7 0 00-1.5 1z"/>',
	search: '<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>', bell: '<path d="M18 8a6 6 0 10-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 01-3.4 0"/>', usb: '<path d="M12 2v14M8 6l4-4 4 4M7 12h10v4a5 5 0 01-10 0z"/>',
	check: '<path d="M20 6L9 17l-5-5"/>', lock: '<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 118 0v4"/>', inbox: '<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.5 5h13L22 12v6a2 2 0 01-2 2H4a2 2 0 01-2-2v-6z"/>',
	users: '<circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0114 0M16 4a4 4 0 010 8M22 21a7 7 0 00-4-6.3"/>', chat: '<path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>', clip: '<path d="M21 11l-9 9a6 6 0 01-8.5-8.5l9-9a4 4 0 015.7 5.7l-9 9a2 2 0 01-2.8-2.8l8.3-8.3"/>',
	chart: '<path d="M3 3v18h18M7 15l4-4 3 3 5-6"/>', cal: '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>', win: '<path d="M3 5l8-1v8H3zM13 4l8-1v9h-8zM3 13h8v7l-8-1zM13 13h8v8l-8-1z"/>', apple: '<path d="M16 3c0 2-1.5 3.5-3.5 3.5 0-2 1.5-3.5 3.5-3.5zM12 7c1.5 0 2.5-1 4-1 2 0 3.5 1.5 4 3-3 1.5-3 6 .5 7.5-.8 2.5-2.5 5.5-4.5 5.5-1.5 0-2-1-4-1s-2.5 1-4 1c-2.5 0-6-5-6-10 0-3.5 2.2-5.5 4.5-5.5 1.5 0 2.5 1 3.5 1z"/>',
}
export const ic = (n: string, s = 16) => `<svg class="ic" viewBox="0 0 24 24" style="width:${s}px;height:${s}px">${IC[n]}</svg>`
const spark = (pts: string, c: string) => `<svg viewBox="0 0 120 30" preserveAspectRatio="none"><defs><linearGradient id="sg${c.slice(1)}" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="${c}" stop-opacity=".35"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></linearGradient></defs><path d="M0 30 L${pts} L120 30Z" fill="url(#sg${c.slice(1)})"/><polyline points="${pts}" fill="none" stroke="${c}" stroke-width="2"/></svg>`
const AVC = ['#7c3aed', '#db2777', '#0ea5e9', '#16a34a', '#f59e0b', '#ef4444', '#14b8a6']
const av = (t: string, i: number, s = 28) => `<span class="av" style="background:${AVC[i % AVC.length]};width:${s}px;height:${s}px">${t}</span>`

export const SCREENS: Record<string, () => string> = {
	d2: () => `<div class="ui u-d2">
		<aside class="side"><div class="logo"><i>D2</i>D2Defense</div><div class="org"><span>DataSirpi · Production</span><span>▾</span></div>
			<span class="nav">${ic('grid')}Overview</span><span class="nav on">${ic('monitor')}Devices<em>128</em></span><span class="nav">${ic('play')}Sessions<em>6</em></span><span class="nav">${ic('pulse')}Activity</span><span class="nav">${ic('code')}Scripts</span><span class="nav">${ic('shield')}Policies</span><span class="nav">${ic('gear')}Settings</span>
			<div class="me">${av('AK', 0)}<div><b>Admin</b><div class="muted">Security team</div></div></div></aside>
		<div class="main"><div class="top"><div class="search">${ic('search')}Search devices, users, sessions<kbd>⌘K</kbd></div><span style="margin-left:auto">${ic('bell', 18)}</span>${av('DS', 1, 30)}</div>
			<div class="body"><div class="row"><div class="grow"><div class="h1">Devices</div><div class="muted">Managed endpoints across all sites · sample data</div></div><span class="btn-ui" style="border:1px solid #2a2440">Export</span><span class="btn-ui" style="background:linear-gradient(90deg,#7c3aed,#db2777);color:#fff">+ Add device</span></div>
				<div class="kpis">
					<div class="kpi card"><span class="muted">Online</span><b>124</b>${spark('0,22 15,18 30,20 45,12 60,14 75,8 90,10 105,6 120,4', '#a78bfa')}</div>
					<div class="kpi card"><span class="muted">At risk</span><b style="color:#fb7185">3</b>${spark('0,10 15,12 30,8 45,14 60,18 75,16 90,20 105,22 120,24', '#fb7185')}</div>
					<div class="kpi card"><span class="muted">Live sessions</span><b>6</b>${spark('0,24 15,20 30,22 45,16 60,18 75,12 90,16 105,10 120,12', '#f472b6')}</div>
					<div class="kpi card"><span class="muted">Scripts run today</span><b>42</b>${spark('0,26 15,22 30,18 45,20 60,12 75,14 90,8 105,10 120,6', '#34d399')}</div></div>
				<div class="grid2"><div class="tbl card"><div class="tabs"><span class="on">All 128</span><span>Online 124</span><span>Offline 4</span><span>At risk 3</span></div>
					<table><thead><tr><th>Device</th><th>User</th><th>Status</th><th>Last seen</th><th>Risk</th></tr></thead><tbody>
					${[['FIN-LT-0142', 'win', 'Anika R.', 'Online', 'now', 18, '#34d399'], ['ENG-MB-0087', 'apple', 'Rohan K.', 'Session live', 'now', 12, '#f472b6'], ['OPS-LT-0021', 'win', 'Meera S.', 'At risk', '2m', 82, '#fb7185'], ['HR-DT-0009', 'win', 'Kiran P.', 'Online', '5m', 24, '#34d399'], ['ENG-MB-0112', 'apple', 'Vikram N.', 'Isolated', '1h', 64, '#fbbf24'], ['FIN-LT-0150', 'win', 'Divya M.', 'Online', 'now', 9, '#34d399']].map((r: any[], i: number) => `<tr><td><div class="row"><span class="os">${ic(r[1])}</span><div><b>${r[0]}</b><div class="muted" style="font-size:11.5px">${r[1] === 'win' ? 'Windows 11' : 'macOS 14'}</div></div></div></td><td><div class="row">${av(r[2].split(' ').map((x: string) => x[0]).join(''), i + 2, 24)}${r[2]}</div></td><td><span class="pill" style="background:${r[6]}22;color:${r[6]}"><span class="dot" style="background:${r[6]}"></span>${r[3]}</span></td><td class="muted">${r[4]}</td><td><div class="risk"><i style="width:${r[5]}%;background:${r[5] > 60 ? '#fb7185' : r[5] > 30 ? '#fbbf24' : '#34d399'}"></i></div></td></tr>`).join('')}
					</tbody></table></div>
					<div class="live card"><div class="row"><b class="grow">Live session</b><span class="pill" style="background:#f472b622;color:#f472b6">View only</span></div>
						<div class="desk"><span class="rec"><span class="dot" style="background:#ef4444"></span>REC 12:41</span><span class="w" style="left:8%;top:18%;width:52%;height:52%"></span><span class="w" style="left:44%;top:34%;width:46%;height:48%;background:#fff"></span><span class="bar"></span></div>
						<div class="row" style="font-size:12px">${av('RK', 3, 24)}<span class="grow">Rohan K. → ENG-MB-0087</span><span class="btn-ui" style="height:28px;background:#221d31;font-size:12px">Take control</span></div>
						<b style="margin-top:4px">Activity</b>
						<div class="feed"><div><span class="fi" style="background:#fb718522;color:#fb7185">${ic('usb', 14)}</span><span>USB storage blocked on OPS-LT-0021</span><span class="muted">2m</span></div><div><span class="fi" style="background:#34d39922;color:#34d399">${ic('check', 14)}</span><span>Script <b>patch-kb503</b> passed validation</span><span class="muted">8m</span></div><div><span class="fi" style="background:#a78bfa22;color:#a78bfa">${ic('lock', 14)}</span><span>Policy "Finance laptops" updated</span><span class="muted">21m</span></div></div></div></div></div></div></div>`,
	nft: () => `<div class="ui u-nft"><div class="top"><span class="brandw">AVIS</span><nav><span style="color:#fff">Explore</span><span>Drops</span><span>Create</span><span>Activity</span></nav><div class="srch">${ic('search')}Search items, collections, creators</div><span class="wallet">◆ Connect wallet</span></div>
		<div class="hero"><div><div class="h1">Discover, collect and sell <span>rare digital art</span></div><p style="color:#b3a9d6;font-size:15px;max-width:44ch;margin:14px 0 0">Mint your work as an NFT, list it in minutes and trade with collectors on-chain.</p><div class="row" style="margin-top:18px"><span class="btn-ui" style="background:#efeaff;color:#1a1330">Explore</span><span class="btn-ui" style="border:1px solid #3a2e5e">Create NFT</span></div><div class="stats"><div><b>Artworks</b><span>Minted by creators</span></div><div><b>Auctions</b><span>Live bidding</span></div><div><b>Wallets</b><span>MetaMask, WalletConnect</span></div></div></div>
			<div class="feat art-1"><div class="meta"><div class="row">${av('LN', 1, 30)}<div><b>Aurora Drift #12</b><div style="font-size:11.5px;color:#b3a9d6">@lunanova</div></div></div><div style="text-align:right"><div style="font-size:11px;color:#b3a9d6">Current bid</div><b>1.25 ETH</b></div></div></div></div>
		<div class="chips"><span class="on">All</span><span>Art</span><span>Music</span><span>Photography</span><span>3D</span><span>Collectibles</span></div>
		<div class="cards">${[['Neon Tide #7', '0.80', 2], ['Solar Bloom', '2.40', 3], ['Night Grid #3', '0.45', 4], ['Pulse Field', '1.10', 5]].map((c, i) => `<div class="nc"><div class="art art-${c[2]}"></div><div class="row"><b class="grow">${c[0]}</b>${av(['KA', 'MR', 'JS', 'PT'][i], i, 22)}</div><div class="row" style="margin-top:6px"><span class="grow" style="color:#b3a9d6;font-size:12px">${c[1]} ETH</span><span class="bid">Place bid</span></div></div>`).join('')}</div></div>`,
	integra: () => `<div class="ui u-int"><div class="rail"><i class="lg">DS</i><i class="on">${ic('inbox', 18)}</i><i>${ic('users', 18)}</i><i>${ic('chart', 18)}</i><i>${ic('gear', 18)}</i></div>
		<div class="list"><div class="lh"><h2>Inbox</h2><div class="ch"><span class="on">All 24</span><span>WhatsApp 9</span><span>Email 7</span><span>Instagram 5</span><span>Web chat 3</span></div></div>
			${[['Priya S.', 'Hi, my order hasn’t arrived yet', '2m', '#22c55e', 1], ['Arjun K.', 'Re: Invoice for March', '14m', '#0ea5e9', 0], ['Meera R.', 'Do you ship to Kochi?', '31m', '#e1306c', 0], ['Rahul V.', 'Thanks, that fixed it!', '1h', '#f59e0b', 0], ['Sneha T.', 'Can I change my plan?', '2h', '#22c55e', 0], ['Imran A.', 'Refund status please', '3h', '#0ea5e9', 0]].map((c: any[], i: number) => `<div class="cv${i === 0 ? ' on' : ''}"><span class="chb">${av(c[0].split(' ').map((x: string) => x[0]).join(''), i + 1, 36)}<em style="background:${c[3]}"></em></span><div style="min-width:0"><b>${c[0]}</b><small>${c[1]}</small></div><time>${c[2]}</time></div>`).join('')}</div>
		<div class="chat"><div class="chh">${av('PS', 1, 38)}<div class="grow"><b style="font-size:15px">Priya S.</b><div style="font-size:12px;color:#62807a">via WhatsApp · Order #1042</div></div><span class="pill" style="background:#ecfdf9;color:#0f766e">Assigned to you</span><span class="btn-ui" style="background:#0f766e;color:#fff">Resolve</span></div>
			<div class="msgs"><div style="align-self:center;font-size:11.5px;font-weight:600;color:#88a19c;background:#e7efed;padding:3px 10px;border-radius:999px">Today</div><div class="b them">Hi, I placed an order on Monday.</div><div class="b them">Hi, my order hasn’t arrived yet. It was supposed to come yesterday.</div><div class="b me">Sorry about that, Priya. Let me check the courier for you.</div><div class="b me">It left the warehouse this morning and arrives today by 6 pm.<div class="prod"><i></i><div><b>Order #1042</b><div style="font-size:12px;color:#62807a">Out for delivery · 2 items</div></div></div></div><div class="b them">Great, thank you so much! 🙏</div></div>
			<div class="sugg"><span>Share tracking link</span><span>Offer a discount</span><span>Close conversation</span></div><div class="comp">${ic('clip', 18)}<span>Type a reply…</span><span class="send">Send</span></div></div>
		<div class="prof"><div style="display:grid;justify-items:center;gap:6px;text-align:center">${av('PS', 1, 64)}<b style="font-size:16px">Priya Sharma</b><span style="font-size:12px;color:#62807a">priya@example.com · +91 90000 00000</span><div class="row"><span class="tag" style="background:#fef3c7;color:#92400e">VIP</span><span class="tag" style="background:#e0f2fe;color:#075985">Repeat buyer</span></div></div>
			<b>Timeline</b><div class="tl"><div><b>Order #1042</b> out for delivery<div style="color:#88a19c;font-size:11.5px">Today, 09:12</div></div><div><b>Email</b> campaign clicked<div style="color:#88a19c;font-size:11.5px">Yesterday</div></div><div><b>Ticket</b> resolved by Rahul<div style="color:#88a19c;font-size:11.5px">12 Mar</div></div></div></div></div>`,
	hrms: () => `<div class="ui u-hr"><aside class="side"><span class="lg">HRMS</span><span>Dashboard</span><span class="on">People</span><span>Onboarding</span><span>Offboarding</span><span>Roles &amp; access</span><span>Documents</span></aside>
		<div class="main"><div class="row"><div class="h1 grow">People</div><span class="btn-ui" style="background:#1d4ed8;color:#fff">+ Add employee</span></div>
			<div class="cards3"><div class="c card"><span style="color:#6b7a99">Active employees</span><b>248</b></div><div class="c card"><span style="color:#6b7a99">Onboarding</span><b>6</b></div><div class="c card"><span style="color:#6b7a99">Pending approvals</span><b>3</b></div></div>
			<div class="g2"><div class="c card" style="padding:0;overflow:hidden"><table><thead><tr><th>Name</th><th>Department</th><th>Role</th><th>Status</th></tr></thead><tbody>${[['Kavya Nair', 'Engineering', 'Manager', '#16a34a', 'Active'], ['Rahul Menon', 'Design', 'Employee', '#16a34a', 'Active'], ['Ayesha Khan', 'Finance', 'HR admin', '#1d4ed8', 'Onboarding'], ['Joseph T.', 'Sales', 'Employee', '#16a34a', 'Active'], ['Nisha P.', 'Support', 'Employee', '#f59e0b', 'Offboarding']].map((r, i) => `<tr><td><div class="row">${av(r[0].split(' ').map((x: string) => x[0]).join(''), i, 26)}<b>${r[0]}</b></div></td><td>${r[1]}</td><td>${r[2]}</td><td><span class="pill" style="background:${r[3]}1a;color:${r[3]}">${r[4]}</span></td></tr>`).join('')}</tbody></table></div>
				<div class="c card"><b>Onboarding · Ayesha Khan</b><div class="row" style="margin:10px 0"><div class="prog grow"><i style="width:60%"></i></div><span style="font-size:12px">3 / 5</span></div>${[['Offer signed', 1], ['Laptop assigned', 1], ['Accounts created', 1], ['Policy training', 0], ['Manager intro', 0]].map((c) => `<div class="chk"><i class="${c[1] ? 'y' : ''}">${c[1] ? '✓' : ''}</i>${c[0]}</div>`).join('')}</div></div></div></div>`,
	trojan: () => `<div class="ui u-tr"><div class="top"><span class="lg">Trojan</span><span style="font-weight:600">Equipment</span><span>Bookings</span><span>Customers</span><span>Reports</span><span style="margin-left:auto" class="btn-ui">${ic('cal')}This week</span></div>
		<div class="body"><div class="row" style="gap:14px"><div class="e card grow"><span class="muted">On rent</span><b style="display:block;font-size:24px">18</b></div><div class="e card grow"><span class="muted">Available</span><b style="display:block;font-size:24px;color:#16a34a">11</b></div><div class="e card grow"><span class="muted">In service</span><b style="display:block;font-size:24px;color:#64748b">3</b></div><div class="e card grow"><span class="muted">Returns due today</span><b style="display:block;font-size:24px;color:#ea580c">4</b></div></div><div class="eq">${[['Excavator', 'Available', '#16a34a'], ['Forklift', 'Booked', '#ea580c'], ['Boom lift', 'Available', '#16a34a'], ['Generator', 'Maintenance', '#64748b']].map((e) => `<div class="e card"><div class="pic"><svg viewBox="0 0 60 40" fill="#9a3412"><rect x="6" y="20" width="30" height="10" rx="2"/><rect x="12" y="12" width="14" height="10" rx="2"/><path d="M36 22l12-12 6 3-12 12z"/><circle cx="12" cy="33" r="4"/><circle cx="30" cy="33" r="4"/></svg></div><div class="row" style="margin-top:10px"><b class="grow">${e[0]}</b><span class="pill" style="background:${e[2]}1a;color:${e[2]}">${e[1]}</span></div></div>`).join('')}</div>
			<div class="gantt card"><div class="gr"><b>Bookings</b><div class="row" style="justify-content:space-between;font-size:11.5px;color:#9a7a60"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div>${[['Excavator · EX-04', 5, 40, '#ea580c', 'Site A'], ['Forklift · FL-11', 30, 45, '#f59e0b', 'Warehouse'], ['Boom lift · BL-02', 58, 30, '#16a34a', 'Tower B'], ['Generator · GN-07', 12, 22, '#64748b', 'Service'], ['Excavator · EX-09', 44, 34, '#ea580c', 'Site C'], ['Scissor lift · SL-03', 2, 26, '#16a34a', 'Mall fit-out'], ['Forklift · FL-14', 70, 28, '#f59e0b', 'Port']].map((g) => `<div class="gr"><span>${g[0]}</span><div class="gt"><i style="left:${g[1]}%;width:${g[2]}%;background:${g[3]}">${g[4]}</i></div></div>`).join('')}</div></div></div>`,
	viva: () => `<div class="ui u-vv"><div class="top"><span class="lg">Viva-Vita</span><nav><span>Shop</span><span>Our story</span><span>Recipes</span><span>Contact</span></nav><span class="cart">Cart · 2</span></div>
		<div class="hero"><div><div class="h1">Pure coconut,<br><em>cold pressed.</em></div><p>Cold-pressed coconut goodness, from the farm to your kitchen. No additives, ever.</p><span class="shop">Shop now →</span></div>
			<div class="coco"><svg viewBox="0 0 400 420" style="width:100%;height:100%"><circle cx="210" cy="220" r="150" fill="#e7dcc3"/><circle cx="170" cy="230" r="112" fill="#6b4226"/><circle cx="170" cy="230" r="86" fill="#fbf8f0"/><circle cx="296" cy="170" r="70" fill="#5a3620"/><circle cx="296" cy="170" r="50" fill="#fff"/><path d="M270 60c30-40 90-40 110-10-40-5-70 10-90 40z" fill="#2f7d32"/><path d="M250 70c-10-45 30-80 70-70-30 20-45 45-45 80z" fill="#4c9a3f"/></svg></div></div>
		<div class="prods">${[['Virgin coconut oil', '500 ml'], ['Coconut water', '6 × 330 ml'], ['Coconut milk', '400 ml']].map((p) => `<div class="pc"><i></i><div><b>${p[0]}</b><div style="font-size:12px;color:#5a7a5d">${p[1]}</div></div></div>`).join('')}</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding:34px 48px 0">${[['100% natural', 'Nothing added, nothing taken away'], ['Cold pressed', 'Keeps the flavour and nutrients'], ['Farm to bottle', 'Traceable from the grove']].map((f) => `<div style="border-top:2px solid #143018;padding-top:12px"><b style="font-family:var(--serif);font-style:italic;font-weight:400;font-size:26px">${f[0]}</b><div style="font-size:13px;color:#3b5a3e">${f[1]}</div></div>`).join('')}</div></div>`,
	fg: () => `<div class="ui u-fg"><div class="fg-cover"></div><div class="pf"><span class="big"></span><div><b style="font-size:20px">@futuregril</b><div style="font-size:12.5px;color:#c9a3b6">Collector · joined 2021</div></div><div class="st"><div><b>24</b><span>Owned</span></div><div><b>8</b><span>Created</span></div><div><b>1.2k</b><span>Followers</span></div></div></div>
		<div class="tb"><span class="on">Owned</span><span>Created</span><span>Activity</span></div>
		<div class="gr">${[['Ember #4', 3], ['Rose Circuit', 1], ['Dusk Tile', 4], ['Halo #9', 5]].map((c) => `<div><i class="art-${c[1]}"></i><b>${c[0]}</b></div>`).join('')}</div>
		<div class="sheet"><b style="font-size:16px">Transfer NFT</b><span style="font-size:12px;color:#7a4a60">Send “Ember #4” to another wallet</span><div class="in">0x71C…9A3f</div><div class="go">Transfer</div></div></div>`,
}
export const SCREEN_OF: Record<string, ['d' | 'p', string]> = { d2: ['d', 'd2'], nft: ['d', 'nft'], integra: ['d', 'integra'], hrms: ['d', 'hrms'], trojan: ['d', 'trojan'], viva: ['d', 'viva'], fg: ['p', 'fg'] }

/** Device frames as HTML strings (used by client-built views and the case-study markup). `.fit[data-lazy]` is filled
 * with the screen when it comes near the viewport. */
export const screenFit = (id: string) => { const [k] = SCREEN_OF[id]; return `<div class="fit" data-lazy="${id}"><div class="scr scr--${k}"></div></div>` }
export const laptop = (id: string) => `<div class="dev dev--laptop" aria-hidden="true"><div class="dev__lid">${screenFit(id)}</div><div class="dev__base"></div></div>`
export const phoneDev = (id: string) => `<div class="dev dev--phone" aria-hidden="true"><span class="dev__island"></span>${screenFit(id)}</div>`
export const device = (id: string) => (SCREEN_OF[id][0] === 'p' ? phoneDev(id) : laptop(id))
export const browserDev = (id: string) => SCREEN_OF[id][0] === 'p' ? phoneDev(id) : `<div class="dev dev--browser" aria-hidden="true"><div class="dev__bar"><i></i><i></i><i></i><span>Illustrative UI</span></div>${screenFit(id)}</div>`
